### ISSUE TITLE
Twitch channel points

### ISSUE THREAD

**Issue by ahmedtds** [kaneyxx/twitchio-AFKBot#1]
Can you update this to work with and farm Twitch Channel Points please? Sadly staying only on the chat is not enough to gain channel points.

**Comment by kaneyxx** [comment]
> Can you update this to work with and farm Twitch Channel Points please? Sadly staying only on the chat is not enough to gain channel points.

Twitch didn't provide API for farming channel points, you can use selenium to farm that
